version: '3.9'

services:
  mongo:
    image: mongo
    hostname: mongo
    container_name: blockchain-database-mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  back:
    build:
      context: ./backend
    depends_on:
      - mongo
    hostname: blockchain-backend
    container_name: blockchain-backend
    restart: "no"
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/blockchain-database-mongo
  
  front:
    build:
      context: ./frontend
    depends_on:
      - back
    container_name: blockchain-frontend
    restart: "no"
    ports:
      - 5173:5173
    environment:
      - VITE_BACKEND_URL=http://back:3000
      
volumes:
  mongo:
    name: mongo-data
