openapi: 3.0.0
info:
  title: XRP Wallet API
  version: 1.0.0
  description: API for managing XRP wallets and authentication.

paths:

  /api/auth/create-wallet:
    post:
      summary: Create a new XRP wallet
      tags: 
        - AuthWallets
      description: Generates a new XRP wallet, including address, public key and seed, for the user.
      requestBody:
        required: false
      responses:
        '200':
          description: Successfully created a new wallet.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  wallet:
                    type: object
                    properties:
                      address:
                        type: string
                      publicKey:
                        type: string
              example:
                success: true
                wallet:
                  address: "rT3hR7u4EjkTyUv5g1txfM8VEXAMPLe99v"
                  publicKey: "EDuKd5MRNxSpxXm8qkjF7sXkzVJXvhB8W5"

        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
              example:
                success: false
                error: "Server error during wallet creation."

  /api/auth/login:
    post:
      summary: Login with an XRP wallet using a seed
      tags: 
        - AuthWallets
      description: Authenticates a user by validating their XRP wallet seed and returns a JWT token for session management.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - seed
              properties:
                seed:
                  type: string
                  description: The seed of the XRP wallet used for authentication.
            example:
              seed: "s████████████████████████████"
      responses:
        '200':
          description: Successfully logged in and generated a JWT token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  wallet:
                    type: object
                    properties:
                      address:
                        type: string
                      publicKey:
                        type: string
                  token:
                    type: string
              example:
                success: true
                wallet:
                  address: "rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv"
                  publicKey: "ED████████████████████████████████"
                token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '400':
          description: Missing seed in the request body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
              example:
                success: false
                error: "Seed is missing!!!!!!!"
        '401':
          description: Invalid seed provided.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
              example:
                success: false
                error: "Invalid seed"

  /api/rwa/create:
    post:
      summary: Create a new RWA token
      tags:
        - RWAs
      description: Mints a new RWA (Real World Asset) token by creating metadata and submitting the transaction to the XRP ledger.
      security:
        - bearerAuth: []  # Indicates the use of JWT token for authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - description
                - valuation
                - location
                - size
                - seed
              properties:
                name:
                  type: string
                  description: Name of the RWA.
                description:
                  type: string
                  description: Description of the RWA.
                valuation:
                  type: number
                  description: Valuation of the RWA.
                location:
                  type: string
                  description: Location of the RWA.
                size:
                  type: string
                  description: Size of the RWA.
                seed:
                  type: string
                  description: The seed of the XRP wallet used for signing the transaction.
            example:
              name: "Building A"
              description: "A commercial real estate property"
              valuation: 1000000
              location: "New York"
              size: "5000 sqft"
              seed: "s████████████████████████████"
      responses:
        '200':
          description: Successfully created the RWA token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  tokenId:
                    type: string
                    description: The token ID of the newly created RWA.
                  metadata:
                    type: object
                    properties:
                      name:
                        type: string
                      description:
                        type: string
                      valuation:
                        type: number
                      properties:
                        type: object
                        properties:
                          location:
                            type: string
                          size:
                            type: string
                      createdAt:
                        type: string
                        format: date-time
              example:
                tokenId: "abc123456"
                metadata:
                  name: "Building A"
                  description: "A commercial real estate property"
                  valuation: 1000000
                  properties:
                    location: "New York"
                    size: "5000 sqft"
                  createdAt: "2024-12-13T00:00:00Z"
        '400':
          description: Missing required fields in the request body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Missing fields"
        '500':
          description: Internal server error when creating the RWA token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Creation failed"


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # Specifies that the token format is JWT
