openapi: 3.0.0
info:
  title: RWA API
  version: 1.0.0
  description: API for managing Real World Assets on XRPL

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

security:
  - bearerAuth: []

paths:
  /api/auth/connect-wallet:
    post:
      tags: [Auth]
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: object
                  properties:
                    type:
                      type: string
                      default: 'response'
                    result:
                      type: object
                      properties:
                        address:
                          type: string
      responses:
        200:
          description: Wallet connected successfully

  /api/rwa/create:
    post:
      tags: [RWA]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                valuation:
                  type: number
                location:
                  type: string
                size:
                  type: string
                nftId:
                  type: string
      responses:
        200:
          description: RWA created successfully

  /api/rwa/all:
    get:
      tags: [RWA]
      responses:
        200:
          description: List all RWAs except owned ones

  /api/rwa/my-assets:
    get:
      tags: [RWA]
      responses:
        200:
          description: List user's RWAs

  /api/rwa/list-buy-offers:
    post:
      tags: [Offers]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tokenId:
                  type: string
      responses:
        200:
          description: List buy offers for token

  /api/rwa/list-sell-offers:
    post:
      tags: [Offers]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tokenID:
                  type: string
      responses:
        200:
          description: List sell offers for token

  /api/rwa/accept-buy-offer:
    post:
      tags: [Offers]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tokenId:
                  type: string
                walletOwnerBuyRequest:
                  type: string
      responses:
        200:
          description: Buy offer accepted

  /api/rwa/accept-sell-offer:
    post:
      tags: [Offers]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tokenId:
                  type: string
      responses:
        200:
          description: Sell offer accepted

  /api/rwa/get-balance:
    get:
      tags: [Wallet]
      responses:
        200:
          description: Get wallet XRP balance